name: React native build
on:
  release:
    types: [released]

env:
  app_version: ${{ env.RELEASE_VERSION }}
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Rename file
        run: |
          cp android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/ledlink_v${{env.app_version}}.apk
      - name: Upload apk to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GC_CREDENTIALS }}
          path: android/app/build/outputs/apk/release/ledlink_v${{env.app_version}}.apk
          destination: led-link-app.appspot.com/app/
      - name: Rename file
        run: |
          cp android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/ledlink.apk
      - name: Update apk to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GC_CREDENTIALS }}
          path: android/app/build/outputs/apk/release/ledlink.apk
          destination: led-link-app.appspot.com/app/
      

