name: React native build
on:
  push:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      - id: Upload files to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GC_CREDENTIALS }}
          path: android/app/build/outputs/apk/release/app-release.apk
          destination: led-link-app.appspot.com/app/ledlink.apk
      

